// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVq_uXGPr5UFHDm7puyu5bZuaZ_98N4js',
    appId: '1:301741157369:web:1b8b5cce2e2e2d4104eb28',
    messagingSenderId: '301741157369',
    projectId: 'proyecto-llm',
    authDomain: 'proyecto-llm.firebaseapp.com',
    storageBucket: 'proyecto-llm.appspot.com',
    measurementId: 'G-4PETM2FS8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2rrYccbGq86lgYF4lvnfWuWWB8yPkTYc',
    appId: '1:301741157369:android:033eac6562beb4ee04eb28',
    messagingSenderId: '301741157369',
    projectId: 'proyecto-llm',
    storageBucket: 'proyecto-llm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXmBRkOv5-pLHklT52ntOAPwUj_XfFSXE',
    appId: '1:301741157369:ios:67c9472c3477ed8804eb28',
    messagingSenderId: '301741157369',
    projectId: 'proyecto-llm',
    storageBucket: 'proyecto-llm.appspot.com',
    iosClientId: '301741157369-gkgrphd9ugnsgpbvfkl3lcmo5k578a7m.apps.googleusercontent.com',
    iosBundleId: 'com.kdata.llmTrivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXmBRkOv5-pLHklT52ntOAPwUj_XfFSXE',
    appId: '1:301741157369:ios:1c6d02cea335953b04eb28',
    messagingSenderId: '301741157369',
    projectId: 'proyecto-llm',
    storageBucket: 'proyecto-llm.appspot.com',
    iosClientId: '301741157369-755rq6vbdhk22cfehlqp98vg7h5lqodt.apps.googleusercontent.com',
    iosBundleId: 'com.kdata.llmTrivia.RunnerTests',
  );
}
